### ISSUE TITLE
Request - Add Google Voice Support??

### ISSUE THREAD

**Issue by PROBLEMCHYLD** [frimtec/secure-sms-proxy#196]
Do you think it's possible to add Google Voice Support? A feature to import all the contacts at once instead of individually? Thanks for the great app. Also maybe add a backup feature import/export settings.

**Comment by frimtec** [comment]
Hi

"Secure SMS Proxy" is a sidecar app to give other apps in the Google Play Store the chance to send/receive SMS without requesting the SMS permissions which are anyway not granted by Google since about 3 years. 

At the same time "Secure SMS Proxy" gives the user the power to fully control with which phone Numbers the app can exchange SMS. The communication between "Secure SMS Proxy" and the app is encrypted, so that no other app can read the SMS in between.

As of now I'm only aware of one app that uses "Secure SMS Proxy": PAssist. 
If there are other Apps you know, please let me know.

The use of "Google Voice Support" in the context of "Secure SMS Proxy" does not give any meaning to me as of now. 
Can you please specify it in more details?
There is also no contact import feature in the app, as contacts are not imported at all. Therefore a "import all contacts" does not make sense so far.

Please let me know if you want to use "Secure SMS Proxy" for your own app. If you require additional features you can contact me for sure, but be detailed and explain the use cases.

Best regards
Markus
