### ISSUE TITLE
Installing updates don't work until ???

### ISSUE THREAD

**Issue by PROBLEMCHYLD** [frimtec/secure-sms-proxy#215]
Whenever I install a new update it doesn't work until I delete numbers in the Operations Center. This is why I asked to not have all the numbers tied to the delete button. So every update I have to delete all the contacts just to add them all back. This is only on Android 13 OnePlus 8T but works fine on Android 9

**Comment by frimtec** [comment]
Hello @PROBLEMCHYLD 
If it's a game of wasting developers' time with weird requests (your alias suggests it), then I'm asking you to stop it immediately.
Open software developers invest time in projects that they make freely available, wasting their time for nothing is quite unfair.

If I misinterpret the situation, then sorry, but please consider that no support is possible with such an unclear error description.
A serious bug description includes detailed descriptions of the scenario to reproduce, expected behavior, observed behavior, backed up with logs, stack traces, and screenshots.
