### ISSUE TITLE
Sms messangers

### ISSUE THREAD

**Issue by martinLory** [frimtec/secure-sms-proxy#276]
Hello, can you please suggest me some java-based SMS messengers where this project can be implemented?
Thanks for your help and sorry for bothering

**Comment by frimtec** [comment]
Hi @martinLory 

The S2MSP app is a workaround for applications that need SMS permissions but won't get them due to Googles-Playstore restrictions (see https://support.google.com/googleplay/android-developer/answer/9047303?hl=en).

Apps can use S2MSP as SMS proxy, with a very secure approach where the user must explicitly grant permissions, to allow communication between the app and individual phone numbers.

The S2MSP app itself can not be provided in Google-Playstore due to the request of SMS permissions. S2MSP app needs to be installed from alternative sources like github or IzzyOnDroid.
As S2MSP is open source and does not require any other permissions then SMS send/receive (e.g. no internet access etc.), S2MSP is proofed to be very safe and has no risk for the app user.

An SMS messanger app is one of the use cases where Google still grants SMS permissions. Therefore the use of S2MSP for a SMS messagnger app is probably not sensible.

Maybe you can tell me more about your plans why and how you would like to integrate S2MSP in a messanger app?

Regards frimtec

**Comment by frimtec** [comment]
I see your goal.

But let me share my thoughts on this:
* The main goal of S2MSP is to give apps the possibility to use SMS communication even if they not qualified to get the required permissions in the Google-Playstore, while not open any security risks for the app user.
* SMS messenger apps are allowed to request SMS permission in the Google-Playstore. Therefor the burden of integrating S2MSP into an SMS messenger app is quite an overhead.
* Most messenger apps have features to block numbers individually, therefore your use case is already supported by most messenger apps.

Conclusion: Even if I'm happy for each app using S2MSP I would not recommend to use it for the use case that you have in mind.
